//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalLayihesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Advice()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public int id { get; set; }
        public string headText { get; set; }
        public string contentText { get; set; }
        public Nullable<System.DateTime> addDate { get; set; }
        public Nullable<int> cityID { get; set; }
        public Nullable<int> categoryID { get; set; }
        public Nullable<int> imageID { get; set; }
        public Nullable<int> likeID { get; set; }
        public Nullable<int> userID { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual City City { get; set; }
        public virtual İmage İmage { get; set; }
        public virtual Like Like { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
    }
}
