//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalLayihesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int id { get; set; }
        public string content { get; set; }
        public System.DateTime comment_Date { get; set; }
        public int user_ID { get; set; }
        public int advice_ID { get; set; }
    
        public virtual Advice Advice { get; set; }
        public virtual User User { get; set; }
    }
}
